// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nimphoxdxuzaowldejkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pbXBob3hkeHV6YW93bGRlamt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDA5OTksImV4cCI6MjA2NzMxNjk5OX0.7gRtbSEwoGJZVlVmqQiZk7KLoQ89b2KZmUPCkJflkPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});