// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://govrjacwazjfzvvkbenq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdnJqYWN3YXpqZnp2dmtiZW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDE2OTEsImV4cCI6MjA2NzMxNzY5MX0.QDG2-XYMNchcfeB2R9dEvfCTbvAMFSSH0-9n-3b5py4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});